[general]
import = [
	"./themes/tokyo_night_day.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 12 
normal = { family = "Hack Nerd Font", style = "Regular" }

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

